stages:
  - build_stage
  - deploy_stage


build:
  stage: build_stage
  image: node
  script:
    # - apt update -y
    # - apt install npm -y
    - npm install
  artifacts:
    paths:
      - node_modules
      - package-log.json 
  
deploy:
  stage: deploy_stage
  image: node
  script:
    # - apt update -y
    # - apt install nodejs -y
    - node index.js > /dev/null 2>&1 &