name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker --version

      - name: Build Docker Image
        run: docker build -t nodeapp .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Stop and Remove Old Container
        run: |
          docker stop nodeg || true
          docker rm nodeg || true

      - name: Run New Container
        run: docker run -d --name nodeg -p 3000:3000 nodeapp

      - name: Docker Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKER_TOKEN

      - name: Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker tag nodeapp $DOCKERHUB_USERNAME/nodeapp
          docker push $DOCKERHUB_USERNAME/nodeapp
